site_name: Study Docs
theme:
  name: material
  language: ru
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: '#'
nav:
  - home: index.md
  - 'Code guide':
    - 'Правила написания HTML': 'code-guide/02_html.md'
    - 'Правила написания CSS': 'code-guide/03_css.md'

